---

- name: apt public key for nginx
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 561F9B9CAC40B2F7
    state: present

- name: add nginx/passenger and maxmind package repo
  apt_repository: repo={{ item }} state=present
  with_items:
    - "deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ubuntu_dist_name }} main"

- name: install geoipupdate, nginx and two modules
  apt:
    pkg:
      - nginx
      - libnginx-mod-http-passenger
      - libnginx-mod-http-geoip2
      - geoipupdate
    update_cache: yes

- name: ensure nginx service is enabled
  service:
    name: nginx
    enabled: yes

- name: copy blacklist-referrer.conf
  copy:
    src: blacklist-referrer.conf
    dest: /etc/nginx/conf.d/blacklist-referrer.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: add rate limiting
  copy:
    dest: /etc/nginx/conf.d/decidim-rate-limit.conf
    content: |
      limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;
  notify: restart nginx

- name: create nginx decidim.conf
  template:
    src: decidim.conf.j2
    dest: /etc/nginx/sites-enabled/decidim.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: fix mod-http-passenger.conf
  lineinfile:
    path: /etc/nginx/conf.d/mod-http-passenger.conf
    regexp: 'passenger_ruby'
    line: "passenger_ruby {{ decidim_home }}/.rbenv/shims/ruby;"
  notify: restart nginx

- name: Edit GeoIP.conf
  template:
    src: GeoIP.conf.j2
    dest: /etc/GeoIP.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
  when: set_up_geoip

- name: Update the GeoIP2 database
  shell: geoipupdate
  when: set_up_geoip

- name: Add GeoIP2 update to cron
  cron:
    name: update_geoip2
    weekday: '0,3'
    hour: '23'
    minute: '34'
    job: geoipupdate
  when: set_up_geoip

- name: create nginx_geoip.conf
  template:
    src: nginx_geoip.conf.j2
    dest: /etc/nginx/conf.d/nginx_geoip.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
  when: set_up_geoip

# NOTE(d1): https://www.phusionpassenger.com/docs/advanced_guides/troubleshooting/nginx/troubleshooting/ruby/
- name: loosen permissions for passenger
  command: chmod -R g+x,o+x /home/decidim/
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""

- meta: flush_handlers  # run notified handlers now
