---
# Playbook to install Decidim

- hosts: all
  become: true
  vars:
    override_default_file: "{{ lookup('first_found', 'custom_settings/vars.yml', errors='ignore') }}"
  roles:
    - role: common_settings
    - role: init_container
    - role: logrotate
    - role: geerlingguy.clamav
    - role: postgresql
    - role: redis
    - role: bot_blocker
    - role: grzegorznowak.nvm_node
      nvm_node_version: 18.20.4
      nvm_install_globally: ['yarn']
    - role: decidim
