---
roles:
- src: https://github.com/grzegorznowak/ansible-nvm-node.git
  version: master
  name: grzegorznowak.nvm_node
- src: https://github.com/geerlingguy/ansible-role-redis.git
  version: master
  name: geerlingguy.redis
- src: https://github.com/geerlingguy/ansible-role-clamav.git
  version: master
  name: geerlingguy.clamav

collections:
- src: https://github.com/ansible-collections/hetzner.hcloud.git
  version: main
  name: hetzner.hcloud
- src: https://github.com/ansible-collections/community.general.git
  version: main
  name: community.general
