---
# tasks file for init_container

- when: override_default_file is file
  include_vars: "{{ override_default_file }}"

- name: Get facts from local roles
  set_fact:
    matomo_site_id: "{{ matomo_site_id }}"
    # sentry_dsn: "{{ sentry_dsn }}"
  when: set_up_analytics

- name: Remove apt lock files
  file: path={{ item }} state=absent
  with_items:
    - /var/lib/apt/lists/lock
    - /var/cache/apt/archives/lock
    - /var/lib/dpkg/lock-frontend

- name: upgrade all packages in container and autoremove
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: set machine timezone to "{{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: ensure journalctl will not eat whole disk
  replace:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse.*'
    replace: "SystemMaxUse=100M"

- name: restart journald
  become: yes
  systemd: name=systemd-journald state=restarted

- name: add space clearing script
  copy:
    src: clear_up_space.sh
    dest: clear_up_space.sh
    owner: root
    group: root
    mode: '0644'
